name: 'Build Plugin'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build webpack
      working-directory: ./Namo.Plugin.InPlayerEpisodePreview
      run: |
        npm install --save-dev webpack-cli
        npx webpack --config webpack.config.js --env CLIENT=WEB

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name jellyfin-pre "https://nuget.pkg.github.com/jellyfin/index.json"
        dotnet tool install --global dotnet-outdated-tool
        dotnet outdated -pre Always -u -inc Jellyfin

    - name: Retrieve commit identification
      run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --no-restore

    - uses: actions/upload-artifact@v4
      with:
        name: InPlayerEpisodePreview-${{ env.GIT_HASH }}
        path: |
          Namo.Plugin.InPlayerEpisodePreview/bin/Debug/net8.0/Namo.Plugin.InPlayerEpisodePreview.dll